// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5HBaboK9DtPMnHOPNx822IEN4tS3t_Y',
    appId: '1:497332706036:web:6b385f3a3635dfd0519ca1',
    messagingSenderId: '497332706036',
    projectId: 'todo-master-25c60',
    authDomain: 'todo-master-25c60.firebaseapp.com',
    storageBucket: 'todo-master-25c60.firebasestorage.app',
    measurementId: 'G-EWC8C6ZKSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtyziKuu3eXM8rR8p4j1ZLKvHPQ6eYz5s',
    appId: '1:497332706036:android:c8df51ee3cac67f9519ca1',
    messagingSenderId: '497332706036',
    projectId: 'todo-master-25c60',
    storageBucket: 'todo-master-25c60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWhdgZVvq-LMEtlgMENSdgrf1_F-CG7w',
    appId: '1:497332706036:ios:58df587d914855a6519ca1',
    messagingSenderId: '497332706036',
    projectId: 'todo-master-25c60',
    storageBucket: 'todo-master-25c60.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoWhdgZVvq-LMEtlgMENSdgrf1_F-CG7w',
    appId: '1:497332706036:ios:58df587d914855a6519ca1',
    messagingSenderId: '497332706036',
    projectId: 'todo-master-25c60',
    storageBucket: 'todo-master-25c60.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
